# Generated by Django 4.2.7 on 2023-11-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=200)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDjango.userrole')),
            ],
        ),
    ]
